### ISSUE TITLE
Empty SQLDataFrame when all columns spcified as key

### ISSUE THREAD

**Issue by dvantwisk** [Bioconductor/SQLDataFrame#2]
It seems to make sense that all columns in a database could be a key and SQLDataFrame seems to accept this, but:
```
dbfile <- system.file("extdata/test.db", package = "SQLDataFrame")
obj <- SQLDataFrame(dbname = dbfile, dbtable = "colData", dbkey = c('sampleID', 'Treatment', 'Ages')
obj
```
yields:
```
SQLDataFrame with 26 rows and 0 columns
```
where I would have expected an SQLDataFrame with no metadata columns.

**Comment by Liubuntu** [comment]
Hi @dvantwisk , 

The `show` method of `SQLDataFrame` actually requires more than 1 column on the right hand side of the vertical bar to print out the whole thing. The right hand side part looks like the `mcols()` but doesn't work like it. 

The dimension especially the `ncol` counts for the number of non-key columns. So here it shows as `0 columns` and the `show` method checks the the non-key columns when printing. 

Maybe I'll add an message inside the `show` method, that to `Please include at least one column as non-key column for the show method to work`. 

Qian

**Comment by Liubuntu** [comment]
Hi @dvantwisk , 

I have just updated the `show` method to be able to print the `SQLDataFrame` Check the commit here: https://github.com/Bioconductor/SQLDataFrame/commit/2bf356a542fe8ead70446eed4fae50ebb360b0b8

```
 > obj <- SQLDataFrame(dbname = dbfile, dbtable = "colData", dbkey = c('sampleID', 'Treatment', 'Ages'))
!> obj
 SQLDataFrame with 26 rows and 0 columns
     sampleID   Treatment      Ages |
  <character> <character> <integer> |
            a        ChIP        29 |
            b       Input        33 |
            c        ChIP        31 |
            d       Input        23 |
            e        ChIP        35 |
          ...         ...       ... .
            v       Input        39 |
            w        ChIP        40 |
            x       Input        30 |
            y        ChIP        38 |
            z       Input        29 |
```

Let me know if you don't like it or have any suggestions. Thanks!

Best,
Qian
